// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// reorder_once
const arma::mat reorder_once(const arma::mat Y, const arma::uvec o);
RcppExport SEXP _mmsbmdag_reorder_once(SEXP YSEXP, SEXP oSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type o(oSEXP);
    rcpp_result_gen = Rcpp::wrap(reorder_once(Y, o));
    return rcpp_result_gen;
END_RCPP
}
// rgs_mmsbm
List rgs_mmsbm(const arma::mat Y, const arma::uvec o_init, const double alpha_init, const double s_alpha_init, const double a, const double b, const arma::mat A, const arma::mat B, const int n_swap, const int N, const int thin, const int burnin, const int print_freq);
RcppExport SEXP _mmsbmdag_rgs_mmsbm(SEXP YSEXP, SEXP o_initSEXP, SEXP alpha_initSEXP, SEXP s_alpha_initSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ASEXP, SEXP BSEXP, SEXP n_swapSEXP, SEXP NSEXP, SEXP thinSEXP, SEXP burninSEXP, SEXP print_freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type o_init(o_initSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< const double >::type s_alpha_init(s_alpha_initSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type n_swap(n_swapSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type print_freq(print_freqSEXP);
    rcpp_result_gen = Rcpp::wrap(rgs_mmsbm(Y, o_init, alpha_init, s_alpha_init, a, b, A, B, n_swap, N, thin, burnin, print_freq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mmsbmdag_reorder_once", (DL_FUNC) &_mmsbmdag_reorder_once, 2},
    {"_mmsbmdag_rgs_mmsbm", (DL_FUNC) &_mmsbmdag_rgs_mmsbm, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_mmsbmdag(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
